apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  selector:
    matchLabels:
      app: springbootdemo
  replicas: 2 
  template:
    metadata:
      labels:
        app: springbootdemo
    spec:
      containers:
      - name: springboot-container
        image: shreya:v1
        
